package app.kitapla.web;

import app.kitapla.domain.Book;
import app.kitapla.domain.Donation;
import app.kitapla.domain.TargetLevel;
import app.kitapla.domain.User;
import app.kitapla.repo.BookRepository;
import app.kitapla.repo.DonationRepository;
import app.kitapla.repo.UserRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Yarım kalmış bir şema yükseltmesinden arta kalan satır, herkese açık sayfaları düşürmemeli.
 *
 * <p><b>Üretimde olan buydu.</b> {@code users.no_show_count} b27ed88'de NOT NULL olarak
 * eklendi ama varsayılanı yoktu; H2 dolu tabloya böyle bir sütun ekleyemez. Sütun boş
 * değer alabilir hâlde kaldı ve eski üye satırları NULL ile yaşamaya devam etti. d280016
 * {@code @ColumnDefault("0")} ekleyerek <i>bundan sonraki</i> yükseltmeleri düzeltti, ancak
 * hâlihazırda bozulmuş satırlara dokunmadı: Hibernate {@code update} var olan bir sütunu
 * değiştirmez.</p>
 *
 * <p>Alan {@code int} (ilkel tip) olduğu için NULL okunduğunda kutu açma sırasında
 * NullPointerException atılıyor. Keşfet sayfası bağışçıyı {@code join fetch} ile çektiğinden,
 * bozuk üyeye ait <b>tek bir bağış</b> listeye girdiğinde sayfanın tamamı 500 dönüyor.</p>
 *
 * <p>Bu test o satırı birebir kurar: sütun NULL değer içerir ve Hibernate onu geri
 * dolduramaz. Beklenen davranış, bozuk satırın sayfayı düşürmemesi.</p>
 */
@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:kitapla-yarim-yukseltme;DB_CLOSE_DELAY=-1",
        "spring.jpa.hibernate.ddl-auto=update",
        "kitapla.seed.demo=false"
})
@ActiveProfiles("test")
@AutoConfigureMockMvc
class BozukKayitDayaniklilikTest {

    private static final String ESKI_UYE = "eski-bagisci@ornek.com";

    /**
     * Yükseltmenin yarım kaldığı hâliyle users tablosu: no_show_count ve blocked
     * sütunları var ama NOT NULL değil ve mevcut satırda NULL.
     */
    static {
        try (Connection c = DriverManager.getConnection(
                     "jdbc:h2:mem:kitapla-yarim-yukseltme;DB_CLOSE_DELAY=-1", "sa", "");
             Statement s = c.createStatement()) {
            s.execute("""
                    create table users (
                      id bigint generated by default as identity primary key,
                      name varchar(255) not null,
                      email varchar(255) not null unique,
                      password_hash varchar(255) not null,
                      admin boolean not null,
                      student_status varchar(255) not null,
                      school_level varchar(255),
                      document_no varchar(255) unique,
                      document_path varchar(255),
                      address varchar(500),
                      phone varchar(255),
                      created_at timestamp(6) not null,
                      blocked boolean,
                      no_show_count integer
                    )""");
            s.execute("""
                    insert into users
                      (name, email, password_hash, admin, student_status, created_at,
                       blocked, no_show_count)
                    values ('Eski Bagisci', '""" + ESKI_UYE + """
                    ', 'x', false, 'NONE', current_timestamp, null, null)""");
        } catch (Exception e) {
            throw new IllegalStateException("Yarım kalmış şema hazırlanamadı", e);
        }
    }

    @Autowired MockMvc mvc;
    @Autowired UserRepository users;
    @Autowired BookRepository books;
    @Autowired DonationRepository donations;
    @Autowired JdbcTemplate jdbc;

    /**
     * Onarımın gerçekten çalıştığını doğrular. Statik blok satırı NULL olarak kurar;
     * açılışta {@code SemaOnarim} onu varsayılana çekmiş olmalıdır. Bu iddia düşerse
     * aşağıdaki sayfa testleri de boş yere geçiyor demektir.
     */
    @Test
    void acilistaBozukSatirVarsayilanaCekilir() {
        Integer sayac = jdbc.queryForObject(
                "select no_show_count from users where email = ?", Integer.class, ESKI_UYE);
        Boolean askida = jdbc.queryForObject(
                "select blocked from users where email = ?", Boolean.class, ESKI_UYE);

        assertThat(sayac).as("no_show_count doldurulmalı").isZero();
        assertThat(askida).as("blocked doldurulmalı").isFalse();
    }

    @Test
    void bozukUyeninBagisiKesfetSayfasiniDusurmez() throws Exception {
        bagisKur("Dönüşüm");

        mvc.perform(get("/kesfet"))
                .andExpect(status().isOk())
                .andExpect(content().string(containsString("Dönüşüm")));
    }

    @Test
    void bozukUyeninBagisiKitapDetayiniDusurmez() throws Exception {
        Long id = bagisKur("Dönüşüm Detay");

        mvc.perform(get("/kitap/" + id))
                .andExpect(status().isOk())
                .andExpect(content().string(containsString("Dönüşüm Detay")));
    }

    /** Bozuk üyeye ait bir bağış kurar ve kimliğini döndürür. */
    private Long bagisKur(String baslik) {
        User donor = users.findByEmail(ESKI_UYE).orElseThrow();

        Book b = new Book();
        b.setTitle(baslik);
        b.setAuthor("Franz Kafka");
        b = books.save(b);

        Donation d = new Donation();
        d.setDonor(donor);
        d.setBook(b);
        d.setQuantity(3);
        d.setTargetLevel(TargetLevel.HEPSI);
        return donations.save(d).getId();
    }
}
