-- KİTAPLA — V1 Başlangıç Veritabanı Şeması (PostgreSQL & ANSI SQL uyumlu)

-- 1. Üyeler (users)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL DEFAULT FALSE,
    student_status VARCHAR(255) NOT NULL DEFAULT 'NONE',
    school_level VARCHAR(255),
    document_no VARCHAR(255) UNIQUE,
    document_path VARCHAR(255),
    address VARCHAR(500),
    phone VARCHAR(255),
    school VARCHAR(255),
    student_email VARCHAR(255) UNIQUE,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    no_show_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Kitaplar (books)
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    cover_url VARCHAR(1000),
    purchase_link VARCHAR(1000),
    description VARCHAR(1000),
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Kampüs Teslim Noktaları (pickup_points)
CREATE TABLE pickup_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus VARCHAR(120) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(400),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Bağışlar (donations)
CREATE TABLE donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id BIGINT NOT NULL REFERENCES users(id),
    book_id BIGINT NOT NULL REFERENCES books(id),
    description VARCHAR(500),
    quantity INTEGER NOT NULL,
    source VARCHAR(255) NOT NULL DEFAULT 'PURCHASE',
    target_level VARCHAR(255) NOT NULL DEFAULT 'HEPSI',
    status VARCHAR(255) NOT NULL DEFAULT 'OPEN',
    preferred_point_id BIGINT REFERENCES pickup_points(id),
    preferred_point_note VARCHAR(300),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Bağış Talepleri (claims)
CREATE TABLE claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL REFERENCES donations(id),
    student_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(255) NOT NULL DEFAULT 'MATCHED',
    meeting_point_id BIGINT REFERENCES pickup_points(id),
    meeting_note VARCHAR(300),
    meeting_at TIMESTAMP WITH TIME ZONE,
    meeting_arranged_at TIMESTAMP WITH TIME ZONE,
    meeting_reminded_at TIMESTAMP WITH TIME ZONE,
    shipped_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_claims_donation_student UNIQUE (donation_id, student_id)
);

-- 6. Kitap İstekleri (requests)
CREATE TABLE requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id),
    book_id BIGINT NOT NULL REFERENCES books(id),
    description VARCHAR(500),
    status VARCHAR(255) NOT NULL DEFAULT 'OPEN',
    source VARCHAR(255),
    fulfilled_by_id BIGINT REFERENCES users(id),
    fulfilled_at TIMESTAMP WITH TIME ZONE,
    meeting_point_id BIGINT REFERENCES pickup_points(id),
    meeting_note VARCHAR(300),
    meeting_at TIMESTAMP WITH TIME ZONE,
    meeting_arranged_at TIMESTAMP WITH TIME ZONE,
    meeting_reminded_at TIMESTAMP WITH TIME ZONE,
    shipped_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. Takaslık Kitaplar (swap_books)
CREATE TABLE swap_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    book_id BIGINT NOT NULL REFERENCES books(id),
    note VARCHAR(300),
    status VARCHAR(255) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_swap_books_user_book UNIQUE (user_id, book_id)
);

-- 8. Takas Teklifleri (swap_offers)
CREATE TABLE swap_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id BIGINT NOT NULL REFERENCES users(id),
    to_user_id BIGINT NOT NULL REFERENCES users(id),
    offered_swap_book_id BIGINT NOT NULL REFERENCES swap_books(id),
    target_swap_book_id BIGINT NOT NULL REFERENCES swap_books(id),
    message VARCHAR(300),
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    meeting_point_id BIGINT REFERENCES pickup_points(id),
    meeting_note VARCHAR(300),
    meeting_at TIMESTAMP WITH TIME ZONE,
    meeting_arranged_at TIMESTAMP WITH TIME ZONE,
    meeting_reminded_at TIMESTAMP WITH TIME ZONE,
    from_shipped_at TIMESTAMP WITH TIME ZONE,
    to_shipped_at TIMESTAMP WITH TIME ZONE,
    decided_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. Sohbetler (conversations)
CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(255) NOT NULL,
    ref_id BIGINT NOT NULL,
    user_a_id BIGINT NOT NULL REFERENCES users(id),
    user_b_id BIGINT NOT NULL REFERENCES users(id),
    last_message VARCHAR(200),
    last_message_at TIMESTAMP WITH TIME ZONE,
    last_read_a TIMESTAMP WITH TIME ZONE,
    last_read_b TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_conversations_kind_ref UNIQUE (kind, ref_id)
);

CREATE INDEX ix_conv_a ON conversations (user_a_id);
CREATE INDEX ix_conv_b ON conversations (user_b_id);

-- 10. Mesajlar (messages)
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id),
    sender_id BIGINT NOT NULL REFERENCES users(id),
    body VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_msg_conv ON messages (conversation_id, created_at);

-- 11. Bildirimler (notifications)
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    type VARCHAR(255) NOT NULL,
    message VARCHAR(500) NOT NULL,
    read_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 12. Şikâyetler / Raporlar (reports)
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(id),
    kind VARCHAR(255) NOT NULL,
    ref_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    note VARCHAR(1000),
    status VARCHAR(255) NOT NULL DEFAULT 'OPEN',
    reported_user_id BIGINT REFERENCES users(id),
    reviewed_by_id BIGINT REFERENCES users(id),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    admin_note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_report_status ON reports (status);
CREATE INDEX ix_report_target ON reports (kind, ref_id);

-- 13. Bağlantı Jetonları (auth_tokens)
CREATE TABLE auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    type VARCHAR(255) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_auth_token_hash ON auth_tokens (token_hash);
