package app.kitapla.config;

import app.kitapla.domain.User;
import app.kitapla.repo.UserRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Var olan bir veritabanının üstüne yeni sürüm açıldığında şemanın büyüyebildiğini doğrular.
 *
 * <p>Hibernate {@code ddl-auto=update} ile eksik sütunları ekler; ancak sütun NOT NULL ise ve
 * tabloda zaten satır varsa, varsayılan değeri olmayan sütun eklenemez ve uygulama açılışta
 * çöker. Bu yüzden varsayılanı olan her NOT NULL alan {@code @ColumnDefault} taşır.
 * Bu test, o kuralın bozulmasını yakalar.</p>
 */
@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:kitapla-eski-sema;DB_CLOSE_DELAY=-1",
        "spring.jpa.hibernate.ddl-auto=update",
        "kitapla.seed.demo=false"
})
@ActiveProfiles("test")
class SemaGuncellemeTest {

    /** Yeni sütunlar eklenmeden önceki hâliyle, içinde bir üye bulunan users tablosu. */
    static {
        try (Connection c = DriverManager.getConnection(
                     "jdbc:h2:mem:kitapla-eski-sema;DB_CLOSE_DELAY=-1", "sa", "");
             Statement s = c.createStatement()) {
            s.execute("""
                    create table users (
                      id bigint generated by default as identity primary key,
                      name varchar(255) not null,
                      email varchar(255) not null unique,
                      password_hash varchar(255) not null,
                      admin boolean not null,
                      student_status varchar(255) not null,
                      created_at timestamp(6) not null
                    )""");
            s.execute("""
                    insert into users (name, email, password_hash, admin, student_status, created_at)
                    values ('Eski Uye', 'eski@ornek.com', 'x', false, 'NONE', current_timestamp)""");
        } catch (Exception e) {
            throw new IllegalStateException("Eski şema hazırlanamadı", e);
        }
    }

    @Autowired UserRepository users;

    @Test
    void eskiVeritabaniUstuneAcilirVeYeniSutunlarDolar() {
        Optional<User> eski = users.findByEmail("eski@ornek.com");

        assertThat(eski).as("eski satır korunmalı").isPresent();
        assertThat(eski.get().getNoShowCount()).isZero();
        assertThat(eski.get().isBlocked()).isFalse();
    }
}
